name: 'Tech Radar Entry'
description: 'Creates markdown files from closed issues labeled as tech-radar'
inputs:
  gh-token:
    description: 'GitHub token'
    required: true
  label:
    description: 'Label to look for on issues'
    required: false
    default: 'tech-radar'
  target-directory:
    description: 'Directory where to save the markdown files'
    required: false
    default: 'radar'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: "zap"
  color: "blue"
