# This is a basic workflow to help you get started with Actions

name: say_hello

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: "needs-review"
