# This is a basic workflow to help you get started with Actions
name: Say Hello

on:
  workflow_dispatch:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          entry: "Hello World"
          secret: ${{ secrets.GITHUB_TOKEN }}
